FitnessAppEnterprise/Controllers/DetailsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Security.Claims;
using System.Threading.Tasks;
using FitnessAppEnterprise.Models;
using FitnessAppEnterprise.Models.Enums;
using FitnessAppEnterprise.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;

namespace FitnessAppEnterprise.Controllers
{
  [Authorize]
  public class DetailsController : Controller
  {
    private readonly IRemoteService _remoteService;

    public DetailsController(IRemoteService remoteService)
    {
      _remoteService = remoteService;
    }

    // GET: DetailsController
    public ActionResult Index()
    {
      return View();
    }

    // GET: DetailsController/Details/5
    public async Task<ActionResult> Details(int id)
    {
      var model = new List<DetailModel>();
      var userId = GetUserId();

      if (id == (int)ActivityType.Workout)
      {
        model = await _remoteService.GetDetailModels(EndpointType.Workout, userId);
      }
      else if (id == (int)ActivityType.CheatMeals)
      {
        model = await _remoteService.GetDetailModels(EndpointType.CheatMeals, userId);
      }

      return View(model);
    }

    // GET: DetailsController/Create
    public ActionResult Create()
    {
      return View();
    }

    // POST: DetailsController/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Create(IFormCollection collection)
    {
      try
      {
        return RedirectToAction(nameof(Index));
      }
      catch
      {
        return View();
      }
    }

    // GET: DetailsController/Edit/5
    public ActionResult Edit(int id)
    {
      return View();
    }

    // POST: DetailsController/EditWorkout/{id}
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<ActionResult> EditWorkout(int id, WorkoutEditModel model)
    {
      if (id != model.Id)
      {
        return BadRequest();
      }
      var response = await _remoteService.PutDataAsync(EndpointType.Workout, id, model);
      if (response.StatusCode == HttpStatusCode.OK)
      {
        return RedirectToAction("Index", "Home");
      }

      return BadRequest();
    }

    // POST: DetailsController/EditCheatMeal/{id}
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<ActionResult> EditCheatMeal(int id, CheatMealEditModel model)
    {
      if (id != model.Id)
      {
        return BadRequest();
      }
      var response = await _remoteService.PutDataAsync(EndpointType.CheatMeals, id, model);
      if (response.StatusCode == HttpStatusCode.OK)
      {
        return RedirectToAction("Index", "Home");
      }

      return BadRequest();
    }



    // GET: DetailsController/Delete/{id}?activity={activity}
    public async Task<ActionResult> Delete(int id, [FromQuery] int activity)
    {
      HttpResponseMessage message = null;
      switch (activity)
      {
        case 1:
          message = await _remoteService.DeleteAsync(EndpointType.Workout, id);
          break;
        case 2:
          message = await _remoteService.DeleteAsync(EndpointType.CheatMeals, id);
          break;
      }

      if (message == null)
      {
        return NotFound();
      }

      if (message.StatusCode == HttpStatusCode.Accepted)
      {
        return RedirectToAction("Index", "Home");
      }

      return BadRequest();
    }

    // POST: DetailsController/Delete/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Delete(int id, IFormCollection collection)
    {
      try
      {
        return RedirectToAction(nameof(Index));
      }
      catch
      {
        return View();
      }
    }

    private string GetUserId()
    {
      return User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
    }
  }
}

FitnessAppEnterprise/Controllers/WorkoutController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IdentityModel.Tokens.Jwt;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Runtime.Serialization.Formatters.Binary;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using FitnessAppEnterprise.Extensions;
using FitnessAppEnterprise.Models;
using FitnessAppEnterprise.Models.Enums;
using FitnessAppEnterprise.Services.Implementations;
using FitnessAppEnterprise.Services.Interfaces;
using IdentityModel.Client;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Html;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Razor.TagHelpers;
using Newtonsoft.Json;

namespace FitnessAppEnterprise.Controllers
{
  public class WorkoutController : Controller
  {
    private readonly IHttpClientFactory _clientFactory;
    private readonly IRemoteService _remoteService;

    public WorkoutController(
      IHttpClientFactory clientFactory,
      IRemoteService remoteService)
    {
      _clientFactory = clientFactory;
      _remoteService = remoteService;
    }

    [Authorize]
    public async Task<IActionResult> AddWorkout()
    {
      //var client = _clientFactory.CreateClient("workout_client");
      //var accessToken = await HttpContext.GetTokenAsync("access_token");
      //client.SetBearerToken(accessToken);
      //var response = await client.GetAsync("https://localhost:44379/api/workouttypes/");
      var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var userName = User.FindFirst(ClaimTypes.Email)?.Value;

      //var result = await response.Content.ReadAsStringAsync();
      //var models = JsonConvert.DeserializeObject<List<WorkoutTypeModel>>(result);
      var models = await _remoteService.GetMultipleModelDataAsync<WorkoutTypeModel>(EndpointType.WorkoutTypes, HttpMethod.Get);

      var workoutModel = HttpContext.Session.GetObject<WorkoutAddModel>("workoutModel");
      if (workoutModel == null)
      {
        workoutModel = new WorkoutAddModel()
        {
          UserId = userId,
          WorkoutTypes = models,
          Fields = new Dictionary<string, double>(),
          Created = DateTime.Today
        };
      }

      HttpContext.Session.SetObject("workoutModel", workoutModel);

      return View(workoutModel);
    }

    [Authorize]
    [HttpPost]
    public async Task<IActionResult> AddWorkout(WorkoutAddModel model)
    {
      if (ModelState.IsValid)
      {
        var response = await _remoteService.PostDataAsync(EndpointType.Workout, model);

        if (response.StatusCode == HttpStatusCode.OK)
        {
          HttpContext.Session.Remove("workoutModel");
          return RedirectToAction("Index", "Home");
        }
      }

      return View("Error");
    }

    [Authorize]
    [HttpPost]
    public async Task<IActionResult> WorkoutTypeChanged(WorkoutAddModel model)
    {
      var selectedValue = model.SelectedWorkoutType;
      //var client = _clientFactory.CreateClient();
      //var accessToken = await HttpContext.GetTokenAsync("access_token");
      //client.SetBearerToken(accessToken);
      //var response = await client.GetAsync($"https://localhost:44379/api/workouttypes/{selectedValue}");

      //var result = await response.Content.ReadAsStringAsync();
      //var fields = JsonConvert.DeserializeObject<Dictionary<string, double>>(result);
      var fields = await _remoteService.GetSingleModelDataAsync<Dictionary<string, double>>(EndpointType.WorkoutTypes,
        HttpMethod.Get, param: selectedValue.ToString());
      var workoutModel = HttpContext.Session.GetObject<WorkoutAddModel>("workoutModel");
      workoutModel.Fields = fields;
      workoutModel.SelectedWorkoutType = selectedValue;
      HttpContext.Session.SetObject("workoutModel", workoutModel);

      return RedirectToAction(nameof(AddWorkout));
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
      return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
  }
}

FitnessAppEnterprise/Views/Shared/_CheatMealEditModal.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@using System.Globalization
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model CheatMealEditModel
@{
    var day = Model.Created.Day;
    var month = Model.Created.Month;
    var date = string.Empty;
    var dayTxt = string.Empty;
    var monthTxt = string.Empty;

    if (day < 10)
    {
        dayTxt = $"0{day}";
    }
    else
    {
        dayTxt = day.ToString();
    }

    if (month < 10)
    {
        monthTxt = $"0{month}";
    }
    else
    {
        monthTxt = month.ToString();
    }

    date = string.Concat(Model.Created.Year, "-", monthTxt, "-", dayTxt);
}

<div class="modal fade" id="@ViewData["editModalId"]" tabindex="-1" role="dialog" aria-labelledby="editModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Edit Cheat meal</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form asp-controller="Details" asp-action="EditCheatMeal" asp-route-id="@Model.Id" method="post">
                <div class="modal-body">
                    <div class="form-group row">
                        <label class="col-sm-4 col-form-label">Meal Type</label>
                        <div class="col-sm-4">
                            @Model.MealType
                            <input type="hidden" name="Model.Id" value="@Model.Id" />
                            <input type="hidden" name="Model.MealType" value="@Model.MealType" />
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-4 col-form-label">Date</label>
                        <div class="col-sm-4">
                            <input type="date" name="Model.Created" value="@date" />
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-4 col-form-label">Amount (g)</label>
                        <div class="col-sm-4">
                            <input type="text" name="Model.MealAmount" value="@Model.MealAmount" class="form-control" />
                        </div>
                    </div>
                    <input type="hidden" name="Model.UserId" value="@Model.UserId" />
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save changes</button>
                </div>
            </form>
        </div>
    </div>
</div>

FitnessAppEnterprise/Views/Shared/_CheatMealViewModal.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model CheatMealEditModel
@{
  var date = string.Concat(Model.Created.Year, "-", Model.Created.Month, "-", Model.Created.Day);
}

<div class="modal fade" id="@ViewData["viewModalId"]" tabindex="-1" role="dialog" aria-labelledby="viewModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">View Cheat meal</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-group row">
                    <label class="col-sm-4 col-form-label">Meal Type</label>
                    <div class="col-sm-4">
                        <p>@Model.MealType</p>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-4 col-form-label">Date</label>
                    <div class="col-sm-4">
                        <p>@Model.Created.ToString("yyyy MMMM dd")</p>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-4 col-form-label">Amount (g)</label>
                    <div class="col-sm-4">
                        <p>@Model.MealAmount</p>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

FitnessAppEnterprise/Views/Shared/_DailyCheatMeals.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model List<CheatMealEditModel>
@{
}

<div class="modal fade" id="@ViewData["cheatMealModalId"]" tabindex="-1" role="dialog" aria-labelledby="editModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Edit Workout</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                @foreach (var modelItem in Model)
                {
                    <div class="card card-body">
                        <div class="form-group row">
                            <label class="col-sm-4 col-form-label">Cheat Meal Type</label>
                            <div class="col-sm-4 col-form-label">
                                @modelItem.MealType
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-sm-4 col-form-label">Date</label>
                            <div class="col-sm-4 col-form-label">
                                @modelItem.Created
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-sm-4 col-form-label">Amount (g)</label>
                            <div class="col-sm-4 col-form-label">
                                @modelItem.MealAmount
                            </div>
                        </div>
                    </div>
                }
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

FitnessAppEnterprise/Views/Shared/_DailyDetail.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@using FitnessAppEnterprise.Helpers
@model DailyDetailModel
@inject DateHelper DateHelper
@{
    var title = DateHelper.GetMonthAndDate(Model.Created);
    var text = string.Empty;
    var activitiesExist = true;
    var workoutsExist = Model.Workouts.Any();
    var cheatMealsExist = Model.CheatMeals.Any();
    var workoutModal = string.Empty;
    var cheatMealModal = string.Empty;
    if (workoutsExist)
    {
        workoutModal = $"{DateHelper.GetMonthAndDateNoGap(Model.Created)}workouts";
        ViewData["workoutModalId"] = workoutModal;
    }
    if (cheatMealsExist)
    {
        cheatMealModal = $"{DateHelper.GetMonthAndDateNoGap(Model.Created)}cheatmeals";
        ViewData["cheatMealModalId"] = cheatMealModal;
    }

    if (!workoutsExist && !cheatMealsExist)
    {
        activitiesExist = false;
        text = "No workouts/cheatmeals";
    }
    else
    {
        text = $"{Model.Workouts.Count} workouts/{Model.CheatMeals.Count} cheat meals";
    }
}

<div class="card card-body mr-2 box-shadow mt-3">
    <div class="row">
        <div class="col-lg-4">
            <h4>@title</h4>
        </div>
        <div class="col-lg-4">
            <div class="text-muted">
                <p>@text</p>
            </div>
        </div>
        @if (activitiesExist)
        {
            <div class="col-lg-4 float-right">
                @if (workoutsExist)
                {
                    <a class="btn btn-success text-white mr-1" data-toggle="modal" data-target="#@workoutModal">
                        <i class="fa-solid fa-person-running"></i>
                    </a>
                }
                @if (cheatMealsExist)
                {
                    <a class="btn btn-danger text-white mr-1" data-toggle="modal" data-target="#@cheatMealModal">
                        <i class="fa-solid fa-bowl-food"></i>
                    </a>
                }
                <a asp-action="Report" asp-controller="WeeklyView" asp-route-date="@Model.Created" class="btn btn-secondary text-white mr-1">
                    <i class="fa-solid fa-receipt"></i>
                </a>
                @*<form asp-action="Report" asp-controller="WeeklyView" method="post">
                    <input type="hidden" name="created" value="@Model.Created"/>
                </form>*@
            </div>
        }
    </div>
</div>

@if (workoutsExist)
{
    @await Html.PartialAsync("_DailyWorkouts", Model.Workouts, ViewData);
}
@if (cheatMealsExist)
{
    @await Html.PartialAsync("_DailyCheatMeals", Model.CheatMeals, ViewData);
}

FitnessAppEnterprise/Views/Shared/_DailyWorkouts.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model List<WorkoutEditModel>
@{
}

<div class="modal fade" id="@ViewData["workoutModalId"]" tabindex="-1" role="dialog" aria-labelledby="editModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Edit Workout</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                @foreach (var modelItem in Model)
                {
                    <div class="card card-body">
                        <div class="form-group row">
                            <label class="col-sm-4 col-form-label">Workout Type</label>
                            <div class="col-sm-4 col-form-label">
                                @modelItem.WorkoutType
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-sm-4 col-form-label">Date</label>
                            <div class="col-sm-4 col-form-label">
                                @modelItem.Created
                            </div>
                        </div>
                        @foreach (var field in modelItem.Fields)
                        {
                            <div class="form-group row">
                                <label class="col-sm-4 col-form-label">@field.Key</label>
                                <div class="col-sm-4 col-form-label">
                                    @field.Value
                                </div>
                            </div>
                        }
                    </div>
                }
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

FitnessAppEnterprise/Views/Shared/_Detail.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@using FitnessAppEnterprise.Models.Enums
@using FitnessAppEnterprise.Services.Interfaces
@using System.Net.Http
@inject IRemoteService RemoteService
@model DetailModel
@{
    var editModal = string.Empty;
    var viewModal = string.Empty;
    var editModalId = string.Empty;
    var viewModalId = string.Empty;
    var activity = string.Empty;
    WorkoutEditModel workoutEditModel = null;
    CheatMealEditModel cheatMealEditModel = null;
    if (Model.ActivityType == (int)ActivityType.Workout)
    {
        workoutEditModel = await RemoteService.GetSingleModelDataAsync<WorkoutEditModel>(EndpointType.Workout,
                                    HttpMethod.Get, "editDetail", Model.Id.ToString());
        editModal = "_WorkoutEditModal";
        viewModal = "_WorkoutViewModal";
        activity = "workout";
    }
    else if (Model.ActivityType == (int)ActivityType.CheatMeals)
    {
        cheatMealEditModel = await RemoteService.GetSingleModelDataAsync<CheatMealEditModel>(EndpointType.CheatMeals,
            HttpMethod.Get, "editDetail", Model.Id.ToString());
        editModal = "_CheatMealEditModal";
        viewModal = "_CheatMealViewModal";
        activity = "cheatmeal";
    }

    editModalId = $"editModal{activity}{Model.Id}";
    viewModalId = $"viewModal{activity}{Model.Id}";
    ViewData["editModalId"] = editModalId;
    ViewData["viewModalId"] = viewModalId;
}

<div class="card card-body mr-2 box-shadow">
    <div class="row">
        <div class="col-lg-4">
            <h4>@Model.Title</h4>
            <p>@Model.Created.ToString("MM/dd/yyyy")</p>
        </div>
        <div class="col-lg-8">
            <div class="float-right">
                <a class="btn btn-info mr-1" data-toggle="modal" data-target="#@viewModalId">
                    <span>View</span>
                </a>
                <a class="btn btn-secondary mr-1" data-toggle="modal" data-target="#@editModalId">
                    <span>Edit</span>
                </a>
                <a asp-controller="Details" asp-action="Delete" asp-route-id="@Model.Id" asp-route-activity="@Model.ActivityType" class="btn btn-danger mr-1">
                    <span>delete</span>
                </a>
            </div>
        </div>
    </div>
</div>

@*view modal*@
@if (Model.ActivityType == (int)ActivityType.Workout)
{
    @await Html.PartialAsync(viewModal, workoutEditModel, ViewData)
}
else if (Model.ActivityType == (int)ActivityType.CheatMeals)
{
    @await Html.PartialAsync(viewModal, cheatMealEditModel, ViewData)
}

@*edit modal*@
@if (Model.ActivityType == (int)ActivityType.Workout)
{
    @await Html.PartialAsync(editModal, workoutEditModel, ViewData)
}
else if (Model.ActivityType == (int)ActivityType.CheatMeals)
{
    @await Html.PartialAsync(editModal, cheatMealEditModel, ViewData)
}

FitnessAppEnterprise/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FitnessAppEnterprise</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
    <style>
        body {
            background-image: url("https://cdn.pixabay.com/photo/2020/03/23/17/14/run-4961494_1280.jpg");
            background-repeat: round;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-transparent border-bottom box-shadow mb-5 text-primary">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <span class="text-white">FitnessAppEnterprise</span>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Profile">Profile</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Workout" asp-action="AddWorkout">Workouts</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="CheatMeal" asp-action="CheatMealHome">Cheat Meals</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Predictions" asp-action="Predictions">Predictions</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="WeeklyView" asp-action="Index">Weekly View</a>
                            </li>
                        }
                    </ul>
                    <a class="btn btn-danger text-white my-2 my-sm-0"asp-controller="Home" asp-action="Logout">
                        <i class="bi bi-box-arrow-in-right">Logout</i>
                    </a>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - FitnessAppEnterprise - <a asp-area="" asp-controller="Home" asp-action="Profile">Profile</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/font-awesome/js/all.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

FitnessAppEnterprise/Views/Shared/_WorkoutEditModal.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@using System.Globalization
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model WorkoutEditModel
@{
    var day = Model.Created.Day;
    var month = Model.Created.Month;
    var date = string.Empty;
    var dayTxt = string.Empty;
    var monthTxt = string.Empty;

    if (day < 10)
    {
        dayTxt = $"0{day}";
    }
    else
    {
        dayTxt = day.ToString();
    }

    if (month < 10)
    {
        monthTxt = $"0{month}";
    }
    else
    {
        monthTxt = month.ToString();
    }

    date = string.Concat(Model.Created.Year, "-", monthTxt, "-", dayTxt);
    
}

<div class="modal fade" id="@ViewData["editModalId"]" tabindex="-1" role="dialog" aria-labelledby="editModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Edit Workout</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form asp-controller="Details" asp-action="EditWorkout" asp-route-id="@Model.Id" method="post">
                <div class="modal-body">
                    <div class="form-group row">
                        <label class="col-sm-4 col-form-label">Workout Type</label>
                        <div class="col-sm-4">
                            @Model.WorkoutType
                            <input type="hidden" name="Model.Id" value="@Model.Id" />
                            <input type="hidden" name="Model.WorkoutType" value="@Model.WorkoutType" />
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-4 col-form-label">Date</label>
                        <div class="col-sm-4">
                            <input type="date" name="Model.Created" class="form-control" value="@date" />
                        </div>
                    </div>
                    @foreach (var field in Model.Fields)
                    {
                        <div class="form-group row">
                                <label class="col-sm-4 col-form-label">@field.Key</label>
                                <div class="col-sm-4">
                                    <input type="hidden" name="Model.Fields[@field.Key].Key" value="@field.Key"/>
                                    <input type="text" name="Model.Fields[@field.Key].Value" class="form-control" value="@field.Value"/>
                                    <input type="hidden" name="Model.Fields.Index" value="@field.Key"/>
                                </div>
                        </div>
                    }
                    <input type="hidden" name="Model.UserId" value="@Model.UserId" />
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save changes</button>
                </div>
            </form>
        </div>
    </div>
</div>