FitnessAppEnterprise/Controllers/WeeklyViewController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using FitnessAppEnterprise.Extensions;
using FitnessAppEnterprise.Helpers;
using FitnessAppEnterprise.Models;
using FitnessAppEnterprise.Models.Enums;
using FitnessAppEnterprise.Services.Interfaces;
using Microsoft.AspNetCore.Http;

namespace FitnessAppEnterprise.Controllers
{
  public class WeeklyViewController : Controller
  {
    private readonly IRemoteService _remoteService;
    private readonly DateHelper _dateHelper;

    public WeeklyViewController(
      IRemoteService remoteService,
      DateHelper dateHelper)
    {
      _remoteService = remoteService;
      _dateHelper = dateHelper;
    }

    [HttpGet]
    public async Task<IActionResult> Index(DateTime date)
    {
      if (date == DateTime.MinValue)
      {
        date = DateTime.Today;
      }

      if (date > DateTime.Today)
      {
        date = DateTime.Today;
        ViewData["disableRightBtn"] = true;
      }
      var weeklyText = _dateHelper.CreateWeekText(date);
      ViewData["weeklyText"] = weeklyText;
      ViewData["date"] = date;

      // make the request
      var request = new WeeklyViewRequestModel()
      {
        Date = date,
        UserId = GetUserId()
      };

      var response =
        await _remoteService.PostDataWithSpecialParamsAsync<WeeklyViewRequestModel, List<DailyDetailModel>>(
          EndpointType.WeeklyViews, request, "details");

      if (!response.Any())
      {
        ViewData["responseFound"] = false;
      }
      else
      {
        HttpContext.Session.SetString("weeklyModel", "");
        HttpContext.Session.SetObject("weeklyModel", response);
      }
      return View(response);
    }

    [HttpGet]
    public async Task<IActionResult> Report(DateTime date)
    {
      var weeklyModels = HttpContext.Session.GetObject<List<DailyDetailModel>>("weeklyModel");
      var model = weeklyModels.Where(wk => wk.Created == date).ToList().FirstOrDefault();

      if (model != null)
      {
        var request = new CreateReportRequestModel()
        {
          UserId = GetUserId(),
          Created = date,
          Workouts = model.Workouts,
          CheatMeals = model.CheatMeals
        };

        var response = await _remoteService.PostDataWithSpecialParamsAsync<CreateReportRequestModel, ReportResponseModel>(EndpointType.Reports, 
                              request, "add");

        if (response != null)
        {
          var dateTxt = _dateHelper.GetMonthAndDateNoGap(response.Created);
          ViewData["reportModalId"] = $"report{dateTxt}";
          return View(response);
        }
      }
      return RedirectToAction(nameof(Index));
    }

    private string GetUserId()
    {
      return User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
    }
  }
}

FitnessAppEnterprise/Views/WeeklyView/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model List<DailyDetailModel>
@{
    var weeklyText = string.Empty;
    var date = DateTime.Today;
    var rightBtnDisabled = false;
    if (ViewData["weeklyText"] != null)
    {
        weeklyText = ViewData["weeklyText"].ToString();
    }
    if (ViewData["date"] != null)
    {
        date = (DateTime)ViewData["date"];
    }
    if (ViewData["disableRightBtn"] != null && bool.TryParse(ViewData["disableRightBtn"].ToString(), out rightBtnDisabled))
    {
    }
}
<div class="container">
    <div class="row">
        <div class="col-sm-12 text-center mb-3">
            <h2>Weekly View</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-2">
            <a asp-action="Index" asp-route-date="@date.AddDays(-7)" class="btn btn-success text-white">
                <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"/>
                </svg>
            </a>
        </div>
        <div class="col-8 text-center">
            <h4>@weeklyText</h4>
        </div>
        <div class="col-2">
            <a asp-action="Index" asp-route-date="@date.AddDays(7)" class="btn btn-success text-white">
                <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-arrow-right" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8z"/>
                </svg>
            </a>
        </div>
    </div>
    @if (Model == null)
    {
        <div class="text-center">
            <div class="alert alert-danger">
                <span>No activity found for this week.</span>
            </div>
        </div>
    }
    else
    {
        @foreach (var model in Model)
        {
            @await Html.PartialAsync("_DailyDetail", model);
        }
    }
</div>

FitnessAppEnterprise/Views/WeeklyView/Report.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@using Newtonsoft.Json
@model ReportResponseModel
@{
}

<div class="modal fade" id="@ViewData["reportModalId"]" tabindex="-1" role="dialog" aria-labelledby="editModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Edit Workout</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-group row">
                    <label class="col-sm-4 col-form-label">Calorie Expenditure</label>
                    <div class="col-sm-4">@Model.CalorieExpenditure</div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-4 col-form-label">Calorie Intake</label>
                    <div class="col-sm-4">@Model.CalorieIntake</div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-4 col-form-label">Difference</label>
                    <div class="col-sm-4">@Model.Gap</div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-4 col-form-label">Calorie Deficit?</label>
                    <div class="col-sm-4">@Model.IsSurplus</div>
                </div>
            </div>
            <div class="modal-footer">
                <a asp-action="Index" asp-controller="WeeklyView" type="button" 
                        class="btn btn-secondary" 
                        data-dismiss="modal">Close</a>
            </div>
        </div>
    </div>
</div>

@section Scripts
{
    <script type="text/javascript">
        $(document).ready(function () {
            var modalId = "#" + "@ViewData["reportModalId"]";
            console.log(modalId);
            $(modalId).modal('show');
        });
    </script>
}